packages:
  - 'packages/*'
  - 'playground/**'
  - 'packages/**/__tests__/**'
  - docs

hoistPattern:
  - postcss # package/vite
  - pug # playground/tailwind: @vue/compiler-sfc
  - eslint-import-resolver-* # eslint-plugin-import-x
shellEmulator: true
autoInstallPeers: false
dedupeInjectedDeps: false
overrides:
  vite: 'workspace:*'
patchedDependencies:
  "http-proxy@1.18.1": "patches/http-proxy@1.18.1.patch"
  "sirv@3.0.1": "patches/sirv@3.0.1.patch"
  "chokidar@3.6.0": "patches/chokidar@3.6.0.patch"
  "dotenv-expand@12.0.2": "patches/dotenv-expand@12.0.2.patch"
peerDependencyRules:
  allowedVersions:
    vite: "*"
  ignoreMissing:
    - "@algolia/client-search"
    - "postcss"
    - "search-insights"
packageExtensions:
  sass-embedded:
    peerDependencies:
      source-map-js: "*"
    peerDependenciesMeta:
      source-map-js:
        optional: true
ignoredBuiltDependencies:
  - core-js
  - es5-ext
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - "bcrypt"
  - "esbuild"
  - "playwright-chromium"
  - "sharp"
  - "simple-git-hooks"
  - "unrs-resolver"
  - "workerd"
