packages:
  - 'packages/*'
  - 'playground/**'
  - 'packages/**/__tests__/**'
  - docs

hoistPattern:
  - postcss # package/vite
  - pug # playground/tailwind: @vue/compiler-sfc
  - eslint-import-resolver-* # eslint-plugin-import-x
shellEmulator: true
autoInstallPeers: false
dedupeInjectedDeps: false
overrides:
  rolldown: $rolldown
  vite: 'workspace:*'
  debug: 'npm:obug@^1.0.2'
patchedDependencies:
  "sirv@3.0.2": "patches/sirv@3.0.2.patch"
  "chokidar@3.6.0": "patches/chokidar@3.6.0.patch"
  "dotenv-expand@12.0.3": "patches/dotenv-expand@12.0.3.patch"
peerDependencyRules:
  allowedVersions:
    vite: "*"
packageExtensions:
  sass-embedded:
    peerDependencies:
      source-map-js: "*"
    peerDependenciesMeta:
      source-map-js:
        optional: true
  '@rollup/plugin-dynamic-import-vars':
    dependencies:
      '@types/estree': ^1.0.0
ignoredBuiltDependencies:
  - core-js
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - "esbuild"
  - "playwright-chromium"
  - "sharp"
  - "simple-git-hooks"
  - "unrs-resolver"
  - "workerd"

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3 # https://github.com/paulmillr/chokidar/issues/1440
  - semver@5.7.2 || 6.3.1
  - tailwindcss@3.4.18
  - undici-types@6.21.0 # https://github.com/nodejs/undici/issues/4666
