import fs from 'node:fs/promises'
import type { CAC, Command } from 'cac'

type CommandOption = Command['options'][number]

export interface FlagData {
  name: string
  type: string
  description: string
}

export async function updateData() {
  await updateCliCoreData()
}

async function updateCliCoreData() {
  let cli: CAC

  try {
    // @ts-expect-error -- not typed
    const mod = await import('../../packages/vite/dist/node/cli.js')
    cli = mod.cli
  } catch {
    // If fail to import, then just skip updating
    return
  }

  const data = {
    '//': 'Auto-generated by docs/.vitepress/updateData.config.ts',
    globalFlags: cli.globalCommand.options.map(cacOptionToFlagData),
    viteDevFlags: cli.commands
      .find((c) => c.name === '')!
      .options.map(cacOptionToFlagData),
    viteBuildFlags: cli.commands
      .find((c) => c.name === 'build')!
      .options.map(cacOptionToFlagData),
    viteOptimizeFlags: cli.commands
      .find((c) => c.name === 'optimize')!
      .options.map(cacOptionToFlagData),
    vitePreviewFlags: cli.commands
      .find((c) => c.name === 'preview')!
      .options.map(cacOptionToFlagData),
  }

  await fs.writeFile(
    new URL('../_data/cli-core.json', import.meta.url),
    JSON.stringify(data, null, 2) + '\n',
  )
}

function cacOptionToFlagData(option: CommandOption): FlagData {
  let description = option.description
  let type = ''

  // Extract leading `[...]` as type info
  const match = /^\[(.+?)\]\s*/.exec(description)
  if (match) {
    type = match[1]
    description = description.slice(match[0].length)
  }

  return {
    name: option.rawName,
    type: type,
    description: capitalize(description),
  }
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1)
}
