import {
  extractChangelogEntry,
  generateChangelog,
  getReleaseTag,
  prepareRelease,
} from '@vitejs/release-scripts'
import { releasePackages, updateTemplateVersions } from './releaseUtils.ts'

function getRequiredEnv(name: string): string {
  const value = process.env[name]
  if (!value) throw new Error(`${name} is required`)
  return value
}

const pkg = process.argv[2]
const githubServerUrl = getRequiredEnv('GITHUB_SERVER_URL')
const githubRepository = getRequiredEnv('GITHUB_REPOSITORY')
const githubRunId = getRequiredEnv('GITHUB_RUN_ID')

const { tag, version } = await prepareRelease({
  packages: releasePackages,
  pkg,
  release: process.argv[3],
  toTag: (pkg, version) => getReleaseTag(pkg, version, 'vite'),
  generateChangelog: async (pkg) => {
    if (pkg === 'create-vite') await updateTemplateVersions()

    await generateChangelog({
      getPkgDir: () => `packages/${pkg}`,
      tagPrefix: pkg === 'vite' ? undefined : `${pkg}@`,
    })
  },
})

const changelog = extractChangelogEntry({
  changelogPath: `packages/${pkg}/CHANGELOG.md`,
  version,
})
const prBody = [
  `${pkg} release PR generated by the Prepare Release workflow: ${githubServerUrl}/${githubRepository}/actions/runs/${githubRunId}`,
  '',
  '## Changelog',
  '',
  changelog,
].join('\n')
const delimiter = '__VITE_RELEASE_PR_BODY_EOF__'

console.log(
  `tag=${tag}\nversion=${version}\npr_body<<${delimiter}\n${prBody}\n${delimiter}`,
)
