name: Issue Labeled

on:
  issues:
    types: [labeled]

jobs:
  reply-labeled:
    if: github.repository == 'vitejs/vite'
    runs-on: ubuntu-slim
    permissions:
      contents: read # to check out the repo for local actions
      issues: write # for actions/issues-helper to update issues
      pull-requests: write # for actions/issues-helper to update PRs
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false

      - name: contribution welcome
        if: github.event.label.name == 'contribution welcome' || github.event.label.name == 'help wanted'
        uses: ./.github/actions/issues-helper
        with:
          actions: "remove-labels"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: "pending triage, needs reproduction"

      - name: remove pending
        if: (github.event.label.name == 'enhancement' || contains(github.event.label.description, '(priority)') || github.event.label.name == 'needs reproduction') && contains(github.event.issue.labels.*.name, 'pending triage')
        uses: ./.github/actions/issues-helper
        with:
          actions: "remove-labels"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: "pending triage"

      - name: needs reproduction
        if: github.event.label.name == 'needs reproduction'
        uses: ./.github/actions/issues-helper
        with:
          actions: "create-comment"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) using a GitHub repository or [StackBlitz](https://vite.new). Issues marked with `needs reproduction` will be closed if they have no activity within 3 days.
          labels: "pending triage"
