name: Issue Close Require

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  close-issues:
    if: github.repository == 'vitejs/vite'
    runs-on: ubuntu-slim
    permissions:
      contents: read # to check out the repo for local actions
      issues: write # for actions/issues-helper to update issues
      pull-requests: write # for actions/issues-helper to update PRs
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false

      - name: needs reproduction
        uses: ./.github/actions/issues-helper
        with:
          actions: "close-issues"
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: "needs reproduction"
          inactive-day: 3
