name: Lock Closed Issues

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read # to check out the repo for local actions
  issues: write # for actions/issues-helper to update issues

jobs:
  action:
    if: github.repository == 'vitejs/vite'
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false

      - uses: ./.github/actions/issues-helper
        with:
          actions: "lock-closed-issues"
          token: ${{ secrets.GITHUB_TOKEN }}
          inactive-day: 14
