name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      package:
        description: Package to release
        required: true
        default: vite
        type: choice
        options:
          - vite
          - create-vite
          - plugin-legacy
      release:
        description: Release type
        required: true
        default: next
        type: choice
        options:
          - next
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
      version:
        description: Specify exact version instead of release type
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ inputs.package }}-${{ inputs.version || inputs.release }}
  cancel-in-progress: false

permissions: {}

jobs:
  prepare:
    if: github.repository == 'vitejs/vite'
    name: Prepare release PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Set node version to 24
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 24
          package-manager-cache: false

      - name: Install deps
        run: pnpm install
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"

      - name: Prepare release
        id: prepare
        env:
          RELEASE: ${{ inputs.version || inputs.release }}
          RELEASE_PACKAGE: ${{ inputs.package }}
        run: |
          node scripts/prepare-release.ts "$RELEASE_PACKAGE" "$RELEASE" >> "$GITHUB_OUTPUT"

      - id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.RELEASE_GITHUB_APP_CLIENT_ID }}
          private-key: ${{ secrets.RELEASE_GITHUB_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}
          permission-contents: write
          permission-pull-requests: write

      - name: Open release PR
        uses: vitejs/release-scripts/action/release-pr@hash # version
        with:
          app-slug: ${{ steps.generate-token.outputs.app-slug }}
          token: ${{ steps.generate-token.outputs.token }}
          package-path: packages/${{ inputs.package }}
          pr-body: ${{ steps.prepare.outputs.pr_body }}
          tag: ${{ steps.prepare.outputs.tag }}
          version: ${{ steps.prepare.outputs.version }}
