name: Semgrep

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2"

permissions: {}

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for upload-sarif to upload SARIF files.
    container:
      image: semgrep/semgrep:1.177.0@sha256:acaac22ffc7b7cc5926de0751b223bce0b2491c33d18422fa72f632c78d81198
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - run: >-
          semgrep scan
          --quiet
          --sarif
          --config auto
          --exclude playground
          --exclude __tests__
          --exclude-rule javascript.lang.security.audit.detect-non-literal-regexp.detect-non-literal-regexp
          > semgrep-results.sarif

      - name: Upload SARIF result
        uses: github/codeql-action/upload-sarif@b96794f015dfd88f77b49b1c93e0fa7110f94c63 # v4.38.0
        with:
          sarif_file: semgrep-results.sarif
