name: Semgrep

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2"

permissions: {}

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for upload-sarif to upload SARIF files.
    container:
      image: semgrep/semgrep:1.171.0@sha256:bdf7013b2c3634a487671158da77c554f531742326b543a9464d2adf6c433ac8
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - run: >-
          semgrep scan
          --quiet
          --sarif
          --config auto
          --exclude playground
          --exclude __tests__
          --exclude-rule javascript.lang.security.audit.detect-non-literal-regexp.detect-non-literal-regexp
          > semgrep-results.sarif

      - name: Upload SARIF result
        uses: github/codeql-action/upload-sarif@e4fba868fa4b1b91e1fdab776edc8cfbe6e9fb81 # v4.37.3
        with:
          sarif_file: semgrep-results.sarif
