name: Semgrep

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2"

permissions: {}

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for upload-sarif to upload SARIF files.
    container:
      image: semgrep/semgrep:1.174.0@sha256:f1f7b71861c7b28b6e0f661225a2c4f58a484f5d0f182465c6d6b3b22f972ade
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - run: >-
          semgrep scan
          --quiet
          --sarif
          --config auto
          --exclude playground
          --exclude __tests__
          --exclude-rule javascript.lang.security.audit.detect-non-literal-regexp.detect-non-literal-regexp
          > semgrep-results.sarif

      - name: Upload SARIF result
        uses: github/codeql-action/upload-sarif@db488ddef3bf6cb639b32c2e9a7c0a7ea8271d28 # v4.37.8
        with:
          sarif_file: semgrep-results.sarif
